version: "1"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - C:/Users/PC-SOURBH/Documents/databases/mongodb/codershouse-data:/data/db
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend/
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file: 
        - ./backend/.env
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - mongodb
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
