export const ACTION={
     JOIN:"JOIN",
     LEAVE:"LEAVE",
     ADD_PEER:"ADD_PEER",
     RELAY_ICE:"RELAY_ICE",
     RELAY_SDP:"RELAY_SDP",
     REMOVE_PEER:"REMOVE_PEER",
     MUTE:"MUTE",
     REMOVE:"REMOVE",
     ADDROOM:"ADDROOM",
     MUTECLIENTAFTERREMOVE:"MUTECLIENTAFTERREMOVE",
     TOTAL:"TOTAL",
     HANDRAISE:"HANDRAISE"
}